name: jarvis_godmode
description: Final Unified God-Mode Build

# यह है वो फिक्स जिसकी गिटहब को तलाश थी
environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  local_auth: ^2.1.7
  shared_preferences: ^2.2.1
  provider: ^6.0.5
