workflows:
  default-workflow:
    name: Android Build
    working_directory: frontend
    environment:
      flutter: stable
      vars:
        JARVIS_AUTH_TOKEN: "mani_jarvis_admin_786"
    scripts:
      - name: Force Clean and Regenerate Android
        script: |
          # पुराना खराब फोल्डर डिलीट करो
          rm -rf android
          # नया और सही स्ट्रक्चर बनाओ
          flutter create .
      - name: Install dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
